"""Mock MondayClient backed by local fixtures (generated by
scripts/import_to_monday.py --mode fixtures). Lets the whole app run end-to-end
with zero external credentials -- useful for development and for anyone testing
this project without a monday.com account.
"""
from __future__ import annotations

import json
from pathlib import Path

FIXTURES_DIR = Path(__file__).resolve().parents[2] / "fixtures"


class MockMondayClient:
    def __init__(self, fixtures_dir: Path = FIXTURES_DIR):
        self._fixtures_dir = fixtures_dir

    def get_work_orders(self) -> list[dict]:
        return json.loads((self._fixtures_dir / "work_orders_items.json").read_text())

    def get_deals(self) -> list[dict]:
        return json.loads((self._fixtures_dir / "deals_items.json").read_text())
